title: ReconWatch
tagline: Learning Cybersecurity in Public
description: A cybersecurity blog with writeups, recon, and purple team insights.

url: "https://reconwatch.me"

lang: en
timezone: Asia/Kolkata

author:
  alias: Bob
  email: reconwatch@proton.me

theme_mode: auto
toc: true

theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

markdown: kramdown
paginate: 5
