remote_theme: "mmistakes/so-simple-theme@3.2.0"

title: "ReconWatch"
tagline: "Learning Cybersecurity in Public"
description: "A cybersecurity blog with writeups, recon, and purple team insights."
url: "https://reconwatch.me"
baseurl: ""  # root of domain

author:
  name: "Bob"
  email: "reconwatch@proton.me"

markdown: kramdown
paginate: 5
paginate_path: /page:num/

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# Optional, but useful:
permalink: /:categories/:title/
timezone: Asia/Kolkata

# Social media (optional)
social:
  github: 3-6-9-0d
  email: reconwatch@proton.me
